import { Description } from "@radix-ui/react-dialog";
import Members from "../community/members/Members";

export const StringConstants = {
    CREATE_A_PAGE : 'Build Your Guild',
    TAGS : 'Tags',
    PAGE_NAME : 'Page Name',
    EDIT_PAGE: 'Edit Page',
    DESCRIPTION: 'Description',
    PAGE_DESCRIPTION: 'Page Description',
    PAGE_TYPE: 'Page Type',
    SELECT_TOPICS: 'Select your Category',
    ABOUT_THE_PAGE: 'Tell us what your page is about',
    FEW_WORDS_ABOUT_PAGE: 'Few words about the page',
    HOME_PAGE: 'Home',
    EXPLORE_PAGE: 'Explore',
    MEMBER: 'Members',
    POSTS: 'Posts',
    ERROR_LOADING_POSTS: 'Error loading posts',
    // UNFOLLOW: 'Unfollow',
    FOLLOWING: 'Following',
    FOLLOW: 'Follow',
    OFFERINGS: 'Offerings',
    NO_OFFERINGS: 'No offerings available yet',
    EDIT: 'Edit',
    DELETE: 'Delete',
    ABOUT: 'About',
    CREATED_BY: 'Created By',
    NO_PROFILE_DATA: 'No profile data available',
    LOADING: 'Loading...',
    CLOSE: 'Close',
    EXPLORE_TOPICS: 'Explore your favorite topics',
    SUBMIT: 'Submit',
    SOMETHING_WRONG: 'Something went wrong. Please try again later',
    ERROR: 'Error',
    BACK_HOME: 'Go back to Home',
    SIGN_IN: 'Sign in',
    SIGN_IN_REQUIRED: 'Sign in required',
    ALREADY_AN_ACCOUNT: 'Already have an account ?',
    CONTINUE_WITH_GOOGLE: 'Continue with Google.',
    OR_CONTINUE_WITH: 'Or continue with',
    PASSWORD: 'Password',
    EMAIL: 'Email',
    NAME: 'Name',
    CREATE_AN_ACCOUNT: 'Create an account',
    ENTER_INFORMATION: 'Enter your information to get started',
    SELECT_A_PAGE: 'Select a Page',
    REPLY: 'Reply',
    USER_NAME: 'User Name',
    HOST: 'Host',
    LIKE: 'Like',
    COMMENT: 'Comment',
    SHARE: 'Share',
    FOLLOWER: 'Follower',
    OWNER: 'Owner',
    MODERATOR: 'Moderator',
    BANNED: 'Banned',
    JOINED: 'Joined',
    AGO: 'ago',
    REMOVE_USER: 'Remove user',
    CONFIRM_REMOVAL: 'Confirm Removal',
    REMOVAL_CONFIRMATION: 'Are you sure you want to remove this user?',
    CANCEL: 'Cancel',
    REMOVE: 'Remove',
    SELECT_CHANNEL_TO_START_CHATTING: 'Please select a channel to start chatting',
    LOADING_POSTS: 'Loading posts...',
    PLEASE_TRY_AGAIN: 'Please try again.',
    HASHTAG: '#',
    NO_POSTS_YET: 'No posts yet',
    NO_POST_AVAILABLE: 'No posts available',
    ERROR_LOADING_PAGES: 'Error loading Pages.',
    PROFILE: 'Profile',
    FEED: 'Feed',
    CREATOR_STUDIO: 'Creator Studio',
    CHANNEL_TYPE: 'Channel type',
    DISCUSSION: 'Discussion',
    CHAT: 'Chat',
    LOCK_CHANNEL_MESSAGE: 'Want to lock your channel?',
    PVT_CHANNEL_MESSAGE: 'Do you want to make this channel private?',
    YES: 'Yes',
    NO: 'No',
    COMMING_SOON: 'Coming soon',
    NO_TRENDING_CATEGORIES: 'No trending categories found',
    CREATE: 'Create',
    VOTE: 'Votes',
    SEARCH_RESULTS_FOR: 'Search Results for',
    NO_RESULTS_FOUND: 'No results found',
    SEARCH: 'Search',
    SEARCH_FOR: 'Search for',
    TRY_SEARCH_WITH_DIFFERENT_KEYWORDS: 'Try searching with different keywsords',
    HOME: 'Home',
    EXPLORE: 'Explore',
    EXPERTS: 'Experts',
    SIGN_OUT: 'Sign out',
    EXPLORE_COMMUNITY: 'Explore Community',
    DURATION: 'Duration',
    DURATION_UNITS: 'Mins',
    TRENDING_POSTS: 'Trending Posts',
    PAGE_FOLLOWED: 'Page followed',
    ADD: 'Add',
    PROFILE_IMAGE: 'Profile Image',
    UPLOAD_IMAGE: 'Upload Image',
    BACKGROUND_IMAGE: 'Background Image',
    PAGE_RULES: 'Page Rules',
    PAGE_CREATION_SUCCESS: 'Page created successfully',
    PAGE_CREATION_FAILED: 'Page creation failed',
    PAGE_UPDATION_SUCCESS: 'Page updated successfully',
    PAGE_UPDATION_FAILED: 'Page updation failed',
    EXPLORE_CREATOR: 'Explore Creators',
    TOP_PAGES: 'Top Pages',
    POSTING_IN: 'Posting in',
    UPDATE_PROFILE_PICTURE_DESCRIPTION: 'Upload a new image to update your profile picture.',

    ADD_OFFERING: 'Add Offering',
    CREATE_NEW_OFFERING: 'Create New Offering',
    EDIT_OFFERING: 'Edit Offering',
    PRICE: 'Price',
    DISCOUNTED_PRICE:'Discounted Price',
    TITLE: 'Title',
    TYPE: 'Type',
    INR: 'INR',

    SUBSCRIBERS:"Subscribers",
    FOLLOWERS:"Followers",
    NO_COMMUNITIES_AVAILABLE: 'No communities available',
    PUBLIC: 'Public',
    SAVE: 'Save'

}

export const OFFERING_TYPES = {
    CONSULTATION: 'Consultation',
}